; raylib includes

extern InitWindow
extern SetTargetFPS
extern WindowShouldClose
extern BeginDrawing
extern ClearBackground
extern EndDrawing
extern CloseWindow

extern DrawFPS
extern DrawRectangle
extern DrawText

LIGHTGRAY equ 0xffc8c8c8
GRAY equ 0xff828282
DARKGRAY equ 0xff505050
YELLOW equ 0xff00f9fd
GOLD equ 0xff00cbff
ORANGE equ 0xff00a1ff
PINK equ 0xffc26dff
RED equ 0xff3729e6
MAROON equ 0xff3721be
GREEN equ 0xff30e400
LIME equ 0xff2f9e00
DARKGREEN equ 0xff2c7500
SKYBLUE equ 0xffffbf66
BLUE equ 0xfff17900
DARKBLUE equ 0xffac5200
PURPLE equ 0xffff7ac8
VIOLET equ 0xffbe3c87
DARKPURPLE equ 0xff7e1f70
BEIGE equ 0xff83b0d3
BROWN equ 0xff4f6a7f
DARKBROWN equ 0xff2f3f4c
WHITE equ 0xffffffff
BLACK equ 0xff000000
BLANK equ 0x00000000
MAGENTA equ 0xffff00ff
RAYWHITE equ 0xfff5f5f5
